### ISSUE TITLE
[Feature Request] API for integrating other applications

### ISSUE THREAD

**Issue by Regner** [exodus4d/pathfinder#274]
Hey,

I have  few applications I have written that provide me with some extra functionality outside of Pathfinder using the map data from Pathfinder. Right now I am doing some funky shit to be able to scrape the page and pull the information I need. It would be REALLY wonderful if Pathfinder offered a real external API for other applications to use.

Regner

**Comment by exodus4d** [comment]
Hi, this is something I have in my mind for a long long time... ;)

Which kind of *API* is in your mind? - Just a simple **read** *API* with current map data (map config, systems, connections)?

If you can live with *JSON* format, it would be very simple to implement. I would use the same *JSON*-Schema as I use for map *im/export*: [example export](https://gist.github.com/exodus4d/ade2dcaaaa0c732b81113cd2a4582ac6). Demo video: [Youtube](https://youtu.be/PVyX_Xzt2Bg?t=1m31s)

#### Tasks

- [ ] Add global **On/Off** configuration (e.g. in `pathfinder.ini`). Default: **Off**
- [ ] Add *simple*(basic) authentication in order to protect the endpoint(s)
- Endpoint
  - [ ] "GetMapData" - by **mapId**

**Comment by Regner** [comment]
I think a basic read API with the map data would be a really good place to start. It solves 99% of the things I would like to do. There are a few times I have wanted to write to add a system or update intel or similar, but very rarely.

**Comment by atkinsj** [comment]
Extending this to include routes would be great as well.

**Comment by Regner** [comment]
@atkinsj Are you talking about the routes to the trade hubs?

**Comment by Regner** [comment]
Just reading this over I wanted to quickly mention that "If you can live with JSON format" would be a big yes. JSON would be the preferred format no matter way.

**Comment by atkinsj** [comment]
@Regner sort of; on that trade hubs pane you can click the magnifying glass and ask for a route to any location (trade hub or otherwise). If this was available from an API endpoint where you could ask for a route between any two arbitrary locations this would be great.

The implementation is there in /api/route, as that's how the ajax works to populate the trade hub pane, so just extending the entire /api routes to be keyable/authenticated remotely would solve this.

**Comment by exodus4d** [comment]
@atkinsj yes :) I would love to provide this as a public API for that. But I´m worried about the server load. The Route calculation algorithm is very CPU intensive. Even now my official VPS runs at about ~90% CPU load. 
So i would have to upgrade my VPS (4 cores -> 8 cores) which would not be a problem, but this costs. Even now I pay a lot for my VPS.

**Comment by rmcginnis** [comment]
@atkinsj What other type of eve apps do you host and are they open source?

**Comment by atkinsj** [comment]
@exodus4d I agree, server load could be an issue and I'm similarly paying for my hosting too. I'm taking a look in to the routing algorithm to see if I can come up with something for the performance of that aspect but I understand blocking the issue as long as we have that problem.

**Comment by johanko** [comment]
SIgning up for this one. I have started making a couple of temporary endpoints until there's something "official". Have made route(with id as params), controller and model for this. But as Fat Free is new to me, I have some problems with my controller and model. Can anyone provide me with a simple, fast(and ugly?) controller to get map(single) array data by id? Just to point me in the right direction. I can do the rest.

**Comment by atkinsj** [comment]
[Here's an example controller.](https://gist.github.com/atkinsj/0196144d266de191fd6d05723e04acb6)

This is for an API endpoint under ./app/main/controller/api. If you want to drop a controller somewhere else it's a different story.

The hardest part for API endpoints will be how you handle authentication IMO as right now Pathfinder doesn't have a way to handle a non-browser user making a request.

**Comment by johanko** [comment]
Exactly what I want, thanks dude! I can make some basic auth and add verification keys.

**Comment by exodus4d** [comment]
Thats correct. I didn´t need authentiation for non-web users for now :) But I´ll implement a full autheitication schema for all endpoints when this issue will be implemented.

In general, you can add your endpoint somewhere in the `api/`folder, but this is not the best place, it should be reserved for Ajax API´s only, that require user authentication (`MyClass extents AccessController`) - Then you can be sure, the endpoint can only be accessed by logged in users.

Ill add some kind of full REST-API in future. This can easily be done by `$f3->map();`function to get all the *GET*, *POST*, *PUT*, *DELETE* function you need for a proper API.: https://fatfreeframework.com/routing-engine#ReST:RepresentationalStateTransfer

**Comment by johanko** [comment]
Ok, awesome :) sounds like a good plan. I got this working. The only thing is the route/controller is also rendering html head(index.html) together with my json output in browser. Can I prevent this?

Also, thanks for this awesome tool @exodus4d

**Comment by exodus4d** [comment]
@johanko The parent `Controller` Class has a `beforeroute();` and `afterroute()` Hook functions, that are called on **any** request. If it´s **not** an Ajax call, a Template is set in the `beforeroute();` function, which is rendered in the `afterroute()` function. Ajax calls don´t have a template (all templates are rendered on the client). 

So a simple `die();` after your `echo json_encode();` would stop the execution of that `afterroute()` function, and no HTML will be rendered. 

Please poke me in the Slack developer chat for mor information. This Issue becomes OffTopic.
