### ISSUE TITLE
[Feature Request] Deleting a wormhole signature or connection should delete the connection or signature respectively associated with it

### ISSUE THREAD

**Issue by Bluedagger21** [exodus4d/pathfinder#803]
Now that #290 implemented, I would like to see a stronger bond between the two signatures that make up a connection. If system has a signature linking to another system that has a signature linking back to the same system, this should signify a "strong" connection. If I delete this connection, both signatures should be removed from the systems. If I delete a single signature, the connection AND complimentary signature should be deleted.

Currently, connections are made regardless of signatures linking systems. I'm not sure if this is a good strategy for the future of this tool. It is frustrating to see that the visual map connections are completely independent from the signature connections.

**Comment by exodus4d** [comment]
Agree. I´ll try to add this in one of the next releases. The reason of not having this right after #290 got implemented is, that I felt uncomfortable with the fact, that an _accidental_ connection delete by a user would also delete its attached signatures.
I will not make this feature "optional" or configurable by either the user or in the map options. The _feature_ itself will come with some _magic_ where users could wonder about signatures disappearing after a connection was deleted.

**Comment by exodus4d** [comment]
#### Tasks:
- [ ] New checkbox for "delete connection" in confirmation popup. If a signatures gets manually deleted

  ![delete_linked_sig_connections](https://user-images.githubusercontent.com/9299033/62885713-d6709a00-bd39-11e9-90fe-91d39cb47e9b.gif)

- [ ] New checkbox for "delete connections" in "signature reader" dialog. If existing "lazy delete" checkbox is active (which is required in order to auto-delete all signatures not found in pasted scan result), the new checkbox becomes enabled.

  ![pL8DgbY](https://user-images.githubusercontent.com/9299033/62885845-2f403280-bd3a-11e9-9b3e-623f341cf154.png)

- [ ] If any of the new "delete connections" checkbox is **active** → a (potentially) linked signature in _target_ system should also be cleared.
